### ISSUE TITLE
characters or words are being written as lines

### ISSUE THREAD

**Issue by prashantguleria** [dinosauria123/gcv2hocr#31]
When running hocr-lines on the produced hocr file, each character and word is displayed as separate line. Libraries like PDF-BOX  aren't able to search multiple words together.

Attaching scrrenshot of hocr-lines of output hocr present in sample directory.
![hocr-lines-output](https://user-images.githubusercontent.com/10485563/68665949-feee7700-0568-11ea-9956-8efb6b2e859b.png)

**Comment by dinosauria123** [comment]
Thank you for your report.
gcv2hocr may be not output correct hocr files. Which version did you used, C or Python ?
I think python version out put is better than C version.
I don't have plan to fix this issue because it is sufficient to make searchable pdf.

**Comment by prashantguleria** [comment]
@dinosauria123 Thanks for your reply. I used python version only.
I did correct the issue but I did in JAVA for microsft OCR output. I think google doesn't provide the information of line bboxes but microsft provides all the necessary information.
